// <auto-generated />
using BlazorEC_Ver2.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEC_Ver2.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230529084457_Catagories")]
    partial class Catagories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEC_Ver2.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movies",
                            Url = "movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video games",
                            Url = "video-games"
                        });
                });

            modelBuilder.Entity("BlazorEC_Ver2.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "I saw my boyfriend kissing my best friend. if that wasn’t enough, I was with a guy whose guts I hate from my class, Go Eun-Hyuk. I was already shaken up… But apparently there’s a given amount of love that a person receives in their lifetime? And the amount of love I’m able to receive is ‘0’??? Soo-Ae, who’s trying to change her pathetic fate, and Eun-Hyuk, who got involved with Soo-Ae, and their headwind operation! She was only going to ‘act’ like she’s cheating on her boyfriend, but she starts to develop feelings for Eun-Hyuk?! This plan… will it truly work?",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/03/29/15/18/tianjin-2185510_1280.jpg",
                            Price = 9.99m,
                            Title = "Pure Love Operation 11"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "It's very wholeosme, It gives, It ate, I honestly loved our mssochist in this story, she was cute, Also can i marry the elf teacher? She's too cute! Anyways I would give the plot a 9.8/10 it has every straight manhwa plot but it's yuri and it ate, The character's are a 10/10 amazing, Splendid, Spectacular, Majestic, Pleasing women. Anything else? A 10/10 overall? 10000000 out of ten.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/11/29/09/16/architecture-1868667_1280.jpg",
                            Price = 7.99m,
                            Title = "Please Bully Me, Miss Villainess!"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Renia is the princess of the Fontiano Empire. Her happy days were now shattered, after she married Duke Clovis Zenov.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/07/19/01/41/clouds-2517653_640.jpg",
                            Price = 8.99m,
                            Title = "Crazy Princess Renia"
                        });
                });

            modelBuilder.Entity("BlazorEC_Ver2.Shared.Product", b =>
                {
                    b.HasOne("BlazorEC_Ver2.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
